prowjob_namespace: default
pod_namespace: test-pods
plank:
  default_decoration_config:
    utility_images:
      clonerefs: "gcr.io/k8s-prow/clonerefs:v20200320-e079f1a17"
      initupload: "gcr.io/k8s-prow/initupload:v20200320-e079f1a17"
      entrypoint: "gcr.io/k8s-prow/entrypoint:v20200320-e079f1a17"
      sidecar: "gcr.io/k8s-prow/sidecar:v20200320-e079f1a17"
    gcs_configuration:
      bucket: prow-artifacts-mcsh
      path_strategy: explicit
    gcs_credentials_secret: gcs-credentials
presubmits:
  mcserverhosting-net/charts:
  - name: lint-server-deployment
    decorate: true
    always_run: true
    skip_report: false
    clone_depth: 0
    spec:
      containers:
      - name: helm
        image: alpine/helm:3.1.2
        command:
        - "/bin/sh"
        args:
        - -c
        - helm lint server-deployment
  - name: lint-ns-deployment
    decorate: true
    always_run: true
    skip_report: false
    clone_depth: 0
    spec:
      containers:
      - name: helm
        image: alpine/helm:3.1.2
        command:
        - "/bin/sh"
        args:
        - -c
        - helm lint ns-deployment